### ISSUE TITLE
Bug Report: @import Must Precede All Other Statements Error

### ISSUE THREAD

**Issue by surendrakumar6350** [amritmaurya1504/Restaurant_POS_System#3]
**Description**  
When using `@import` inside a CSS file with Tailwind CSS and Vite, Vite throws the following error:  
```plaintext
[vite:css][postcss] @import must precede all other statements (besides @charset or empty @layer)
```
The issue occurs because `@import` is placed **after** Tailwind directives like `@tailwind base`, `@tailwind components`, and `@tailwind utilities`.

**Expected Behavior**  
The CSS should compile without errors, and fonts should load properly.  

**Actual Behavior**  
Vite throws a PostCSS error due to incorrect placement of `@import`.  

**Solution**  
The issue can be fixed by **moving `@import` to the top** of the file:  
```css
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@100;400;700&display=swap');

@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  font-family: 'Inter', sans-serif;
}
```

![Image](https://github.com/user-attachments/assets/c9502315-07d3-48a8-9f42-55c202c4aeaa)
